import type { Rule } from "./types.js";

export const RULES: Rule[] = [
  {
    id: "sql-injection",
    title: "SQL Injection",
    severity: "critical",
    category: "injection",
    cwe: "CWE-89",
    owasp: "A03:2021",
    languages: ["js", "ts", "jsx", "tsx", "py", "php", "rb", "java", "go"],
    patterns: [
      /\b(?:query|execute|db\.run|db\.get|db\.all|db\.exec|client\.query|pool\.query)\s*\(\s*`[^`]*\$\{/,
      /\b(?:query|execute|db\.run|db\.get|db\.all|client\.query|pool\.query)\s*\(\s*['"][^'"]*['"]\s*\+/,
      /\.execute\s*\(\s*f["'][^"']*\{/,
      /\.execute\s*\(\s*["'][^"']*["']\s*%/,
      /\.execute\s*\(\s*["'][^"']*["']\.format\s*\(/,
      /mysql_query\s*\(\s*["'][^"']*["']\s*\./,
      /["']SELECT\s.*FROM\s.*WHERE\s.*['"].*\+/i,
      /["']INSERT\s+INTO\s.*VALUES\s.*['"].*\+/i,
      /["']DELETE\s+FROM\s.*WHERE\s.*['"].*\+/i,
      /["']UPDATE\s.*SET\s.*WHERE\s.*['"].*\+/i,
    ],
    negative_patterns: [
      /\.execute\s*\(\s*["'][^"']*["']\s*,\s*[\[(]/,
    ],
  },
  {
    id: "command-injection",
    title: "OS Command Injection",
    severity: "critical",
    category: "injection",
    cwe: "CWE-78",
    owasp: "A03:2021",
    languages: ["js", "ts", "jsx", "tsx", "py", "php", "rb"],
    patterns: [
      /\bexec\s*\(\s*`[^`]*\$\{/,
      /\bexecSync\s*\(\s*`[^`]*\$\{/,
      /\bexec\s*\(\s*['"][^'"]*['"]\s*\+/,
      /\bexecSync\s*\(\s*['"][^'"]*['"]\s*\+/,
      /os\.system\s*\(\s*f?["']/,
      /subprocess\.(?:call|run|Popen)\s*\([^)]*shell\s*=\s*True/,
      /\b(?:system|passthru|shell_exec|popen)\s*\(\s*\$/,
    ],
  },
  {
    id: "xss",
    title: "Cross-Site Scripting (XSS)",
    severity: "high",
    category: "injection",
    cwe: "CWE-79",
    owasp: "A03:2021",
    languages: ["js", "ts", "jsx", "tsx", "html", "php"],
    patterns: [
      /\.innerHTML\s*(?:\+)?=(?!=)/,
      /\.outerHTML\s*(?:\+)?=(?!=)/,
      /document\.write\s*\(/,
      /document\.writeln\s*\(/,
      /dangerouslySetInnerHTML\s*=\s*\{/,
      /\$\s*\([^)]+\)\.html\s*\(/,
      /v-html\s*=/,
      /\[innerHTML\]\s*=/,
    ],
  },
  {
    id: "eval-injection",
    title: "Code Injection via eval()",
    severity: "critical",
    category: "injection",
    cwe: "CWE-94",
    owasp: "A03:2021",
    languages: ["js", "ts", "jsx", "tsx", "py", "php"],
    patterns: [
      /\beval\s*\(\s*(?!['"]use strict)/,
      /new\s+Function\s*\(/,
      /setTimeout\s*\(\s*['"`]/,
      /setInterval\s*\(\s*['"`]/,
    ],
    negative_patterns: [
      /\/\/\s*eslint-disable/,
      /\/\*\s*safe\s*\*\//i,
    ],
  },
  {
    id: "path-traversal",
    title: "Path Traversal",
    severity: "high",
    category: "injection",
    cwe: "CWE-22",
    owasp: "A01:2021",
    languages: ["js", "ts", "jsx", "tsx", "py", "php", "java"],
    patterns: [
      /(?:readFile|readFileSync|createReadStream)\s*\([^)]*(?:req\.|params\.|query\.)/,
      /path\.(?:join|resolve)\s*\([^)]*(?:req\.|params\.|query\.)/,
      /(?:readFile|readFileSync)\s*\([^)]*\+/,
      /open\s*\(\s*(?:request\.|f["'].*\{)/,
    ],
  },
  {
    id: "ssrf",
    title: "Server-Side Request Forgery (SSRF)",
    severity: "high",
    category: "injection",
    cwe: "CWE-918",
    owasp: "A10:2021",
    languages: ["js", "ts", "jsx", "tsx", "py"],
    patterns: [
      /fetch\s*\(\s*(?:req\.(?:query|body|params)|request\.(?:GET|POST|args))/,
      /axios\.(?:get|post|put|delete)\s*\(\s*(?:req\.(?:query|body|params))/,
      /requests\.(?:get|post)\s*\(\s*(?:request\.(?:GET|POST|args)|url)/,
      /http\.request\s*\(\s*(?:req\.(?:query|body|params))/,
    ],
  },
  {
    id: "prototype-pollution",
    title: "Prototype Pollution",
    severity: "high",
    category: "injection",
    cwe: "CWE-1321",
    owasp: "A03:2021",
    languages: ["js", "ts", "jsx", "tsx"],
    patterns: [
      /\.__proto__\s*[=\[]/,
      /\['__proto__'\]\s*=/,
      /\["__proto__"\]\s*=/,
      /Object\.assign\s*\(\s*\{\s*\}\s*,.*(?:req\.|params\.|body\.)/,
    ],
  },
  {
    id: "xxe",
    title: "XML External Entity (XXE)",
    severity: "high",
    category: "injection",
    cwe: "CWE-611",
    owasp: "A05:2021",
    languages: ["js", "ts", "py", "java", "php"],
    patterns: [
      /new\s+DOMParser\s*\(\s*\).*\.parseFromString/,
      /xml\.etree\..*parse\s*\(/,
      /lxml\.etree\..*XMLParser/,
      /DocumentBuilder.*\.parse/,
      /<!ENTITY\s+\w+\s+SYSTEM/,
    ],
  },
  {
    id: "pickle-deserialization",
    title: "Unsafe Deserialization (pickle)",
    severity: "critical",
    category: "injection",
    cwe: "CWE-502",
    owasp: "A08:2021",
    languages: ["py"],
    patterns: [
      /pickle\.loads?\s*\(/,
      /cPickle\.loads?\s*\(/,
      /marshal\.loads?\s*\(/,
      /yaml\.load\s*\([^)]*\)/,
    ],
    negative_patterns: [
      /yaml\.safe_load/,
      /Loader\s*=\s*yaml\.SafeLoader/,
    ],
  },
  {
    id: "open-redirect",
    title: "Open Redirect",
    severity: "medium",
    category: "injection",
    cwe: "CWE-601",
    owasp: "A01:2021",
    languages: ["js", "ts", "jsx", "tsx", "py", "php"],
    patterns: [
      /res\.redirect\s*\([^)]*req\.(?:query|body|params)\./,
      /redirect\s*\([^)]*request\.(?:GET|POST|args)\./,
      /header\s*\(\s*['"]Location:.*\$_(?:GET|POST|REQUEST)/,
    ],
  },
  {
    id: "hardcoded-secret",
    title: "Hardcoded Secret / API Key",
    severity: "critical",
    category: "secrets",
    cwe: "CWE-798",
    owasp: "A07:2021",
    languages: ["js", "ts", "jsx", "tsx", "py", "php", "rb", "java", "cs", "go", "yaml", "json", "env"],
    patterns: [
      /(?:password|passwd|pwd|secret_key|api_key|apikey|auth_token|access_token)\s*[:=]\s*['"][A-Za-z0-9!@#$%^&*+/=]{8,}['"]/i,
      /AKIA[0-9A-Z]{16}/,
      /ghp_[a-zA-Z0-9]{36}/,
      /github_pat_[a-zA-Z0-9_]{82}/,
      /gho_[a-zA-Z0-9]{36}/,
      /sk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20}/,
      /-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----/,
      /sk_live_[a-zA-Z0-9]{24,}/,
      /rk_live_[a-zA-Z0-9]{24,}/,
      /xox[bpors]-[a-zA-Z0-9-]{10,}/,
    ],
    negative_patterns: [
      /process\.env\./,
      /os\.environ/,
      /\$_ENV/,
      /\.env\./,
      /placeholder|example|changeme|xxx|your[_-]?key/i,
    ],
  },
  {
    id: "hardcoded-password",
    title: "Hardcoded Password in Source",
    severity: "critical",
    category: "secrets",
    cwe: "CWE-259",
    owasp: "A07:2021",
    languages: ["js", "ts", "jsx", "tsx", "py", "php", "rb", "java", "cs", "go"],
    patterns: [
      /password\s*=\s*["'][^"']{6,}["']/i,
      /passwd\s*=\s*["'][^"']{6,}["']/i,
      /db_pass\s*=\s*["'][^"']{6,}["']/i,
    ],
    negative_patterns: [
      /process\.env/,
      /os\.environ/,
      /getenv/,
      /config\[/,
      /\.env\b/,
      /placeholder|example|changeme|test|dummy|mock/i,
    ],
  },
  {
    id: "weak-crypto",
    title: "Weak Cryptographic Algorithm (MD5/SHA1)",
    severity: "high",
    category: "crypto",
    cwe: "CWE-327",
    owasp: "A02:2021",
    languages: ["js", "ts", "jsx", "tsx", "py", "java", "cs", "php"],
    patterns: [
      /createHash\s*\(\s*['"]md5['"]\s*\)/i,
      /createHash\s*\(\s*['"]sha1['"]\s*\)/i,
      /hashlib\.md5\s*\(/,
      /hashlib\.sha1\s*\(/,
      /MessageDigest\.getInstance\s*\(\s*['"]MD5['"]/,
      /MessageDigest\.getInstance\s*\(\s*['"]SHA-?1['"]/,
      /md5\s*\(\s*\$/,
      /sha1\s*\(\s*\$/,
    ],
  },
  {
    id: "insecure-random",
    title: "Insecure Random Number Generation",
    severity: "medium",
    category: "crypto",
    cwe: "CWE-338",
    owasp: "A02:2021",
    languages: ["js", "ts", "jsx", "tsx"],
    patterns: [
      /Math\.random\s*\(\s*\)/,
    ],
    negative_patterns: [
      /\/\/.*non[- ]?security/i,
      /\/\/.*ui|animation|color|display/i,
    ],
  },
  {
    id: "timing-attack",
    title: "Timing Attack in String Comparison",
    severity: "medium",
    category: "crypto",
    cwe: "CWE-208",
    owasp: "A02:2021",
    languages: ["js", "ts", "jsx", "tsx"],
    patterns: [
      /(?:password|token|secret|key|hash|signature)\s*===?\s*(?:req\.|request\.|params\.|body\.)/i,
      /if\s*\(\s*(?:req|request)\.\w+\s*===?\s*(?:password|token|secret|apiKey)/i,
    ],
  },
  {
    id: "jwt-none-alg",
    title: "JWT 'none' Algorithm Accepted",
    severity: "critical",
    category: "auth",
    cwe: "CWE-347",
    owasp: "A02:2021",
    languages: ["js", "ts", "jsx", "tsx", "py"],
    patterns: [
      /algorithms\s*:\s*\[.*['"]none['"]/i,
      /jwt\.decode\s*\([^,)]*,\s*(?:None|null|false|options)/,
      /verify\s*=\s*False/,
    ],
  },
  {
    id: "csrf-missing",
    title: "Missing CSRF Protection",
    severity: "medium",
    category: "auth",
    cwe: "CWE-352",
    owasp: "A01:2021",
    languages: ["js", "ts", "jsx", "tsx", "py"],
    patterns: [
      /app\.(?:post|put|patch|delete)\s*\(\s*['"][^'"]+['"]\s*,\s*(?:async\s+)?\(?(?:req|request)/,
    ],
    negative_patterns: [
      /csrf/i,
      /csrfProtection/,
      /csurf/,
      /@csrf_exempt/,
      /webhook/i,
    ],
  },
  {
    id: "debug-info-disclosure",
    title: "Debug / Sensitive Information Disclosure",
    severity: "low",
    category: "config",
    cwe: "CWE-215",
    owasp: "A05:2021",
    languages: ["js", "ts", "jsx", "tsx", "py", "php"],
    patterns: [
      /console\.log\s*\([^)]*(?:password|token|secret|key|api_key|credential)/i,
      /print\s*\([^)]*(?:password|token|secret|key|api_key|credential)/i,
      /DEBUG\s*=\s*True/,
      /app\.run\s*\([^)]*debug\s*=\s*True/,
    ],
  },
  {
    id: "cors-wildcard",
    title: "Permissive CORS Configuration",
    severity: "medium",
    category: "config",
    cwe: "CWE-942",
    owasp: "A05:2021",
    languages: ["js", "ts", "jsx", "tsx", "py", "java"],
    patterns: [
      /['"]Access-Control-Allow-Origin['"]\s*[:,]\s*['"]\s*\*\s*['"]/,
      /cors\s*\(\s*\{\s*origin\s*:\s*(?:true|['"]\*['"])/,
      /CORS_ALLOW_ALL_ORIGINS\s*=\s*True/,
    ],
  },
];
